# 3.1 파이썬을 이용한 기술통계: 1변량 데이터

3.1.1 통계 처리와 scipy

In [ ]:
import numpy as np
import scipy as sp

In [ ]:
%precision 3

'%.3f'

3.1.2 1변량 데이터의 관리

In [ ]:
fish_data = np.array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

3.1.3 합계와 샘플사이즈

In [ ]:
# scipy.sum well be removed
print(sp.sum(fish_data))

40


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: scipy.sum is deprecated and will be removed in SciPy 2.0.0, use numpy.sum instead
  


In [ ]:
print(np.sum(fish_data))

40


In [ ]:
len(fish_data)

10

3.1.4 평균값(기댓값)

In [ ]:
N = len(fish_data)
sum_value = np.sum(fish_data)
mu = sum_value / N
mu

4.000

In [ ]:
print(sp.mean(fish_data))

4.0


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: scipy.mean is deprecated and will be removed in SciPy 2.0.0, use numpy.mean instead
  """Entry point for launching an IPython kernel.


In [ ]:
print(np.mean(fish_data))

4.0


3.1.5 표본분산

In [ ]:
sigma_2_sample = np.sum((fish_data - mu) ** 2) / N
sigma_2_sample

1.200

In [ ]:
print(f"fish_data             : {fish_data}")
print(f"fish_data - mu        : {fish_data - mu}")
print(f"(fish_data - mu) ** 2 : {(fish_data - mu) ** 2}")

fish_data             : [2 3 3 4 4 4 4 5 5 6]
fish_data - mu        : [-2. -1. -1.  0.  0.  0.  0.  1.  1.  2.]
(fish_data - mu) ** 2 : [4. 1. 1. 0. 0. 0. 0. 1. 1. 4.]


In [ ]:
np.sum((fish_data - mu) ** 2)

12.000

In [ ]:
np.var(fish_data, ddof=0)

1.200

3.1.6 불편분산

In [ ]:
# 왜 표본 평균을 활용한 분산 계산은 분산을 과소추정하는 경향이 있는가?
sigma_2 = np.sum((fish_data - mu) ** 2) / (N - 1)
sigma_2

1.333

In [ ]:
np.var(fish_data, ddof=1)

1.333

3.1.7 표준편차

In [ ]:
sigma = np.sqrt(sigma_2)
sigma

1.155

In [ ]:
np.std(fish_data, ddof=1)

1.155

3.1.8 표준화

In [ ]:
fish_data - mu

array([-2., -1., -1.,  0.,  0.,  0.,  0.,  1.,  1.,  2.])

In [ ]:
np.mean(fish_data - mu)

0.000

In [ ]:
fish_data / sigma

array([1.732, 2.598, 2.598, 3.464, 3.464, 3.464, 3.464, 4.33 , 4.33 ,
       5.196])

In [ ]:
np.std(fish_data / sigma, ddof=1)

1.000

In [ ]:
standard = (fish_data - mu) / sigma

3.1.9 그 외의 통계량

In [ ]:
sp.amax(fish_data)
np.max(fish_data)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: scipy.amax is deprecated and will be removed in SciPy 2.0.0, use numpy.amax instead
  """Entry point for launching an IPython kernel.


6

In [ ]:
print(f"sp.amax : {sp.amax(fish_data)}")
print(f"np.max : {np.max(fish_data)}")

sp.amax : 6
np.max : 6


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: scipy.amax is deprecated and will be removed in SciPy 2.0.0, use numpy.amax instead
  """Entry point for launching an IPython kernel.


In [ ]:
print(f"{sp.amin(fish_data)}")
print(f"{np.min(fish_data)}")

2
2


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: scipy.amin is deprecated and will be removed in SciPy 2.0.0, use numpy.amin instead
  """Entry point for launching an IPython kernel.
